server:
  port: 8711

open:
  log:
    transLogDir: D:/tlmall/open/log

spring:
  datasource:
    url: jdbc:mysql://192.168.65.71:3306/tl_mall_open?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tlmall
    password: tlmall123
  #spring.datasource.driver-class-name=com.mysql.jdbc.Driver
    druid:
      filters: stat
      maxActive:   20
      initialSize:   1
      maxWait:   60000
      minIdle:   1
      timeBetweenEvictionRunsMillis:  60000
      minEvictableIdleTimeMillis:  30000
      validationQuery:  select 1
      testWhileIdle:  true
      testOnBorrow:  false
      testOnReturn:  false
      poolPreparedStatements:  true
      maxPoolPreparedStatementPerConnectionSize:  50
      defaultAutoCommit:  true

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.tuling.tulingmall.open.entity
  configuration:
    map-underscore-to-camel-case: false